language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key: 2546e906-648b-419c-a4a8-8a58638535ce
  app: https://hidden-hamlet-51955.herokuapp.com/
  on:
    repo: bhasshaw/carlog
